export const events = {
    skillSaveResolved: "skillSaveResolved",
    skillCreateResolved: "skillCreateResolved",
    skillDeleteResolved: "skillDeleteResolved",
    heroSaveResolved: "heroSaveResolved",

    ownerUnlocked: "ownerUnlocked",
    getUser: "getUser",
    gotUser: "gotUser",
    onEvent: "onEvent",
    checkRights: "checkRights",
    noRights: "noRights",
    saveHero: "saveHero",
    getSkillNames: "getSkillNames",
    gotSkillNames: "gotSkillNames",
    getSkill: "getSkill",
    gotSkill: "gotSkill",
    createSkill: "createSkill",
    deleteSkill: "deleteSkill",
    saveSkill: "saveSkill",
}